project_name: cortexbot
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/cortexbot/cortexbot.go
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
archive:
  replacements:
    darwin: darwin
    linux: linux
    windows: windows
    386: i386
    amd64: amd64
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
