language: go

go:
  - master

addons:
  apt:
    packages:
      - rpm
      - snapd

env:
  - PATH=/snap/bin:$PATH
  - GO111MODULE=on

install:
  - go mod download
  - sudo snap install snapcraft --classic

script:
  - GO111MODULE=off go get golang.org/x/tools/cmd/cover
  - GO111MODULE=off go get github.com/mattn/goveralls
  - go test -v -covermode=count -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
  - rm -f coverage.out

deploy:
  provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
