language: go

go:
  - 1.9
  - "1.10"
  - master

addons:
  apt:
    packages:
      - rpm
      - snapd

env:
  - PATH=/snap/bin:$PATH

install:
  - sudo snap install snapcraft --classic

script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go test -v -covermode=count -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN

deploy:
  provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_GO_VERSION = "1.10"
